grouping = function(text) {
  
  # After working on Scopus:
  text <- gsub("open source", "opensource", text)
  text <- gsub("internet of things", "iot", text)
  text <- gsub("internet  things", "iot", text)
  text <- gsub("internet things", "iot", text)
  text <- gsub("service oriented architecture", "soa", text)
  text <- gsub("service oriented", "soa", text)
  text <- gsub("service-oriented architecture", "soa", text)
  text <- gsub("service-oriented", "soa", text)
  text <- gsub("web services", "webservice", text)
  text <- gsub("web service", "webservice", text)
  text <- gsub("business process modelling", "businessprocessmodelling", text)
  text <- gsub("workflows", "workflow", text)
  text <- gsub("collaborative platform", "collaborativeplatform", text)
  text <- gsub("case study", "casestudy", text)
  text <- gsub("study methodology", "studymethodology", text)
  text <- gsub("cloud computing", "cloud", text)
  text <- gsub("containerization", "containers", text)
  text <- gsub("containerized", "containers", text)
  text <- gsub("containerize", "containers", text)
  text <- gsub("containerizing", "containers", text)
  text <- gsub("container", "containers", text)
  text <- gsub("containerss", "containers", text)
  text <- gsub("large scale", "largescale", text)
  text <- gsub("multi-cloud", "cloud", text)
  text <- gsub("big data", "bigdata", text)
  text <- gsub("clouds", "cloud", text)
  text <- gsub("machine learning", "machinelearning", text)
  text <- gsub(" ml ", " machinelearning ", text)
  text <- gsub("flexible solution", "flexibility", text)
  text <- gsub("migrating", "migration", text)
  text <- gsub("migrated", "migration", text)
  text <- gsub("migrate", "migration", text)
  text <- gsub("scalable", "scalability", text)
  text <- gsub("reliable", "reliability", text)
  text <- gsub("flexible", "flexibility", text)
  text <- gsub("fast", "speed", text)
  text <- gsub("quick", "speed", text)
  text <- gsub("quickly", "speed", text)
  text <- gsub("speedly", "speed", text)
  text <- gsub("speedy", "speed", text)
  text <- gsub("speeding", "speed", text)
  text <- gsub("faster", "speed", text)
  text <- gsub("rapid", "speed", text)
  text <- gsub("operating systems", "operatingsystem", text)
  text <- gsub("operating system", "operatingsystem", text)
  text <- gsub("smart buildings", "smartbuildings", text)
  text <- gsub("smart building", "smartbuildings", text)
  text <- gsub("large-scale", "largescale", text)
  text <- gsub("large scale", "largescale", text)
  text <- gsub("orchestrate", "orchestration", text)
  text <- gsub("orchestrating", "orchestration", text)
  text <- gsub("virtualizing", "virtualization", text)
  text <- gsub("virtual", "virtualization", text)
  text <- gsub("virtualizationization", "virtualization", text)
  text <- gsub("optimizing", "optimization", text)
  text <- gsub("optimized", "optimization", text)
  text <- gsub("optimize", "optimization", text)
  text <- gsub("optimal", "optimization", text)
  text <- gsub("digitalized", "digitalization", text)
  text <- gsub("digitalize", "digitalization", text)
  text <- gsub("digital", "digitalization", text)
  text <- gsub("digitalizationization", "digitalization", text)
  text <- gsub("communicating", "communication", text)
  text <- gsub("communicated", "communication", text)
  text <- gsub("communicate", "communication", text)
  text <- gsub("communications", "communication", text)
  text <- gsub("decomposing", "decomposition", text)
  text <- gsub("decomposed", "decomposition", text)
  text <- gsub("decompose", "decomposition", text)
  text <- gsub("deploying", "deployment", text)
  text <- gsub("deployed", "deployment", text)
  text <- gsub("deployments", "deployment", text)
  text <- gsub("deploy", "deployment", text)
  text <- gsub("deploymentment", "deployment", text)
  text <- gsub("agility", "agile", text)
  text <- gsub("infratructures", "infratructure", text)
  text <- gsub("architectural", "architecture", text)
  text <- gsub("high level", "highlevel", text)
  text <- gsub("low level", "lowlevel", text)
  text <- gsub("configured", "configuration", text)
  text <- gsub("configuring", "configuration", text)
  text <- gsub("configure", "configuration", text)
  text <- gsub("e-commerce", "ecommerce", text)
  text <- gsub("evolving", "evolution", text)
  text <- gsub("evolves", "evolution", text)
  text <- gsub("evolve", "evolution", text)
  text <- gsub("natural language processing", "nlp", text)
  text <- gsub("language processing", "nlp", text)
  text <- gsub("apis", "api", text)
  text <- gsub("neural networks", "neuralnetworks", text)
  text <- gsub("neural network", "neuralnetworks", text)
  text <- gsub("collaborative", "collaboration", text)
  text <- gsub("continuously", "continuous", text)
  text <- gsub("component", "components", text)
  text <- gsub("componentss", "components", text)
  text <- gsub("resource", "resources", text)
  text <- gsub("resourcess", "resources", text)
  text <- gsub("platforms", "platform", text)
  text <- gsub("technologies", "technology", text)
  text <- gsub("challenge", "challenges", text)
  text <- gsub("challengess", "challenges", text)
  text <- gsub("contexts", "contex", text)
  text <- gsub("complex", "complexity", text)
  text <- gsub("complexityity", "complexity", text)
  
  # After working on STO:
  text <- gsub("rest ful", "rest", text)
  text <- gsub("rest full", "rest", text)
  text <- gsub("request", "requests", text)
  text <- gsub("requestss", "requests", text)
  text <- gsub("response", "responses", text)
  text <- gsub("responses", "responses", text)
  text <- gsub("authenticated", "authentication", text)
  text <- gsub("authenticating", "authentication", text)
  text <- gsub("authenticate", "authentication", text)
  text <- gsub("authorizing", "authorization", text)
  text <- gsub("authorized", "authorization", text)
  text <- gsub("authorize", "authorization", text)
  text <- gsub("database", "databases", text)
  text <- gsub(" db ", " databases ", text)
  text <- gsub("gateways", "gateway", text)
  text <- gsub("config ", "configuration ", text)
  text <- gsub("clusters", "cluster", text)
  text <- gsub("implement ", "implementation ", text)
  text <- gsub("instance ", "instances ", text)
  text <- gsub("event ", "events ", text)
  text <- gsub("tokens", "token", text)
  text <- gsub("problems", "problem", text)
  text <- gsub("issues", "issue", text)
  text <- gsub("patterns", "pattern", text)
  text <- gsub("connect ", "connection ", text)
  text <- gsub("connects ", "connection ", text)
  text <- gsub("connections", "connection", text)
  text <- gsub("clients", "client", text)
  text <- gsub("object oriented", "oop", text)
  text <- gsub("object-oriented", "oop", text)
  text <- gsub("back end", "backend", text)
  text <- gsub("back-end", "backend", text)
  text <- gsub("servers", "server", text)
  text <- gsub("message ", "messages", text)
  text <- gsub("spring boot", "springboot", text)
  text <- gsub("tests", "testing", text)
  text <- gsub("test", "testing", text)
  text <- gsub("testinging", "testing", text)
  text <- gsub("endpoints", "endpoint", text)
  text <- gsub("node js", "nodejs", text)
  text <- gsub("queueing", "queue", text)
  text <- gsub("queued", "queue", text)
  
  # After working on Twitter
  text <- gsub("internetofthings", "iot", text)
  text <- gsub("monolithics", "monolithic", text)
  text <- gsub("monoliths", "monolithic", text)
  text <- gsub("monolith", "monolithic", text)
  text <- gsub("monolithicic", "monolithic", text)
  text <- gsub("artificial intelligence", "ai", text)
  text <- gsub("artificialintelligence", "ai", text)
  text <- gsub("continuous delivery", "continuousdelivery", text)
  text <- gsub("continuous integration", "continuousintegration", text)
  text <- gsub(" ci ", " continuousintegration ", text)
  text <- gsub(" cd ", " continuousdelivery ", text)
  text <- gsub("angular js", "angularjs", text)
  text <- gsub("react js", "reactjs", text)
  text <- gsub("cloudcomputing", "cloud", text)
  text <- gsub("iotpic", "iot", text)
  text <- gsub("java ee", "javaee", text)
  text <- gsub("silicon valley", "siliconvalley", text)
  text <- gsub("dot net", "dotnet", text)
  text <- gsub(" net ", "dotnet", text)
  text <- gsub("software defined networkng", "sdn", text)
  text <- gsub("religionsaas", "saas", text)
  text <- gsub("internetofthings", "iot", text)
  text <- gsub("restapis", "rest api", text)
  text <- gsub("rest api", "rest api", text)
  text <- gsub("restful", "rest", text)
  text <- gsub("servicefabric", "fabric", text)
  text <- gsub("jobs", "job", text)
  text <- gsub("containerspic", "containers", text)
  text <- gsub("digitaltransformation", "digitalization", text)
  text <- gsub("awshttps", "aws", text)
  text <- gsub("apispic", "api", text)
  text <- gsub("tutorialpic", "tutorial", text)
  text <- gsub("apachekafka", "kafka", text)
  text <- gsub("azurepic", "azure", text)
  text <- gsub("dddesign", "ddd", text)
  text <- gsub("mongo db", "mongodb", text)
  text <- gsub("rabbit", "rabbitmq", text)
  text <- gsub("webcomponents", "components", text)
  text <- gsub("websockets", "sockets", text)
  text <- gsub("socket", "sockets", text)
  text <- gsub("socketss", "sockets", text)
  text <- gsub("virtual reality", "virtualreality", text)
  text <- gsub(" vr ", " virtualreality ", text)
  text <- gsub("dotnetcore", "dotnet", text)
  text <- gsub("servicefabrichttps", "fabric https", text)
  text <- gsub("netcore", "dotnet", text)
  text <- gsub(" vm ", " virtualization ", text)
  text <- gsub("virtualisation", "virtualization", text)
  text <- gsub("cloudnativelondon", "cloudnative", text)
  text <- gsub("kuberneteshttp", "kubernetes http", text)
  text <- gsub("kuberneteshttps", "kubernetes https", text)
  text <- gsub("mongodbe", "mongodb", text)
  text <- gsub("apidev", "api", text)
  text <- gsub("testdriven", "tdd", text)
  text <- gsub("testdrivendevelopment", "tdd", text)
  text <- gsub("test driven development", "tdd", text)
  text <- gsub("testdrivendevelopment", "tdd", text)
  text <- gsub("tddpic", "tdd", text)
  text <- gsub("apisecurity", "security", text)
  text <- gsub("androidappdev", "android", text)
  text <- gsub("androiddev", "android", text)
  text <- gsub("androidapp", "android", text)
  text <- gsub("reliableservices", "reliability", text)
  text <- gsub("paaspic", "paas", text)
  text <- gsub("iaaspic", "paas", text)
  text <- gsub("springpic", "spring", text)
  text <- gsub("javaeepic", "javaee", text)
  text <- gsub("javapic", "java", text)
  text <- gsub("oss", "opensource", text)
  text <- gsub("javaone", "opensource", text)
  text <- gsub("openlibertyio", "openliberty", text)
  text <- gsub("openlibertyibm", "openliberty", text)
  text <- gsub("ibmopenliberty", "openliberty", text)
  text <- gsub("open liberty", "openliberty", text)
  text <- gsub("openlibertypic", "openliberty", text)
  text <- gsub("startups", "startup", text)
  text <- gsub("springframework", "spring", text)
  text <- gsub("dockerpic", "docker", text)
  text <- gsub("devopshttps", "devops", text)
  text <- gsub("devopshttp", "devops", text)
  text <- gsub("webdev", "devops", text)
  text <- gsub("mobility", "mobile", text)
  text <- gsub("asynchronous", "async", text)
  text <- gsub("asynch", "async", text)
  text <- gsub(" dl ", " deeplearning ", text)
  text <- gsub("restapispic", "rest api", text)
  text <- gsub("restapipic", "rest api", text)
  text <- gsub("restpic", "rest", text)
  text <- gsub("agilepic", "rest", text)
  text <- gsub("aipic", "rest", text)
  text <- gsub("iotpic", "iot", text)
  text <- gsub("testingpic", "iot", text)
  text <- gsub("load balancer", "loadbalancing", text)
  text <- gsub("load balance", "loadbalancing", text)
  text <- gsub("load balancing", "loadbalancing", text)
  text <- gsub("mlpic", "machinelearning", text)
  text <- gsub("cloudpic", "cloud", text)
  text <- gsub("aspnetcore", "aspnet", text)
  text <- gsub("dotnetpic", "aspnet", text)
  text <- gsub("distributedhttps", "distributed https", text)
  text <- gsub("infosecpic", "security", text)
  text <- gsub("infosec", "security", text)
  text <- gsub("jenkinsworld", "jenkinsworld", text)
  text <- gsub("jenkinspic", "jenkins", text)
  text <- gsub("apipic", "api", text)
  text <- gsub("pythonpic", "python", text)
  text <- gsub("rubypic", "api", text)
  text <- gsub("retailpic", "retail", text)
  text <- gsub("frameworkpic", "framework", text)
  text <- gsub("bigdatapic", "bigdata", text)
  text <- gsub("integrationpic", "integration", text)
  text <- gsub("devopspic", "devops", text)
  text <- gsub("awspic", "aws", text)
  text <- gsub("osspic", "opensource", text)
  text <- gsub("autoscaling", "scalability", text)
  text <- gsub("scaling", "scalability", text)
  text <- gsub("datapic", "data", text)
  text <- gsub("ssdpic", "ssd", text)
  text <- gsub("linuxhttps", "linux https", text)
  text <- gsub("linuxpic", "linux", text)
  text <- gsub("dataanalytics", "data analytics", text)
  text <- gsub("cloudanalytics", "cloud analytics", text)
  text <- gsub("javascriptpic", "javascript", text)
  text <- gsub("rtpic", "rt", text)
  text <- gsub("real time", "rt", text)
  text <- gsub("real time", "rt", text)
  text <- gsub("digitalizationtransformation", "digitalization", text)
  text <- gsub("soacloud", "soa cloud", text)
  text <- gsub(" tool ", " tools ", text)
  text <- gsub(" messages ", " messaging ", text)
  text <- gsub(" message ", " messaging ", text)
  text <- gsub("message-oriented", "messaging", text)
  text <- gsub("event-oriented", "events", text)
  text <- gsub("dockercontainers", "docker containers", text)
  text <- gsub("amazonwebservices", "aws", text)
  text <- gsub("amazon webservices", "aws", text)
  text <- gsub("amazon web services", "aws", text)
  text <- gsub("mobileapp ", "mobile ", text)
  text <- gsub("mobilepic", "mobile", text)
  text <- gsub("dockercon ", "docker ", text)
  
  text
}