grouping = function(text) {

text <- gsub("rest ful", "rest", text)
text <- gsub("rest full", "rest", text)
text <- gsub("request", "requests", text)
text <- gsub("requestss", "requests", text)
text <- gsub("response", "responses", text)
text <- gsub("responses", "responses", text)
text <- gsub("authenticated", "authentication", text)
text <- gsub("authenticating", "authentication", text)
text <- gsub("authenticate", "authentication", text)
text <- gsub("authorizing", "authorization", text)
text <- gsub("authorized", "authorization", text)
text <- gsub("authorize", "authorization", text)
text <- gsub("database", "databases", text)
text <- gsub(" db ", " databases ", text)
text <- gsub("gateways", "gateway", text)
text <- gsub("config ", "configuration ", text)
text <- gsub("clusters", "cluster", text)
text <- gsub("implement ", "implementation ", text)
text <- gsub("instance ", "instances ", text)
text <- gsub("event ", "events ", text)
text <- gsub("tokens", "token", text)
text <- gsub("problems", "problem", text)
text <- gsub("issues", "issue", text)
text <- gsub("patterns", "pattern", text)
text <- gsub("connect ", "connection ", text)
text <- gsub("connects ", "connection ", text)
text <- gsub("connections", "connection", text)
text <- gsub("clients", "client", text)
text <- gsub("object oriented", "oop", text)
text <- gsub("object-oriented", "oop", text)
text <- gsub("back end", "backend", text)
text <- gsub("back-end", "backend", text)
text <- gsub("servers", "server", text)
text <- gsub("message ", "messages", text)
text <- gsub("spring boot", "springboot", text)
text <- gsub("tests", "testing", text)
text <- gsub("test", "testing", text)
text <- gsub("testinging", "testing", text)
text <- gsub("endpoints", "endpoint", text)
text <- gsub("node js", "nodejs", text)
text <- gsub("queueing", "queue", text)
text <- gsub("queued", "queue", text)

}