grouping = function(text) {

text <- gsub("internetofthings", "iot", text)
text <- gsub("monolithics", "monolithic", text)
text <- gsub("monoliths", "monolithic", text)
text <- gsub("monolith", "monolithic", text)
text <- gsub("monolithicic", "monolithic", text)
text <- gsub("artificial intelligence", "ai", text)
text <- gsub("artificialintelligence", "ai", text)
text <- gsub("continuous delivery", "continuousdelivery", text)
text <- gsub("continuous integration", "continuousintegration", text)
text <- gsub(" ci ", " continuousintegration ", text)
text <- gsub(" cd ", " continuousdelivery ", text)
text <- gsub("angular js", "angularjs", text)
text <- gsub("react js", "reactjs", text)
text <- gsub("cloudcomputing", "cloud", text)
text <- gsub("iotpic", "iot", text)
text <- gsub("java ee", "javaee", text)
text <- gsub("silicon valley", "siliconvalley", text)
text <- gsub("dot net", "dotnet", text)
text <- gsub(" net ", "dotnet", text)
text <- gsub("software defined networkng", "sdn", text)
text <- gsub("religionsaas", "saas", text)
text <- gsub("internetofthings", "iot", text)
text <- gsub("restapis", "rest api", text)
text <- gsub("rest api", "rest api", text)
text <- gsub("restful", "rest", text)
text <- gsub("servicefabric", "fabric", text)
text <- gsub("jobs", "job", text)
text <- gsub("containerspic", "containers", text)
text <- gsub("digitaltransformation", "digitalization", text)
text <- gsub("awshttps", "aws", text)
text <- gsub("apispic", "api", text)
text <- gsub("tutorialpic", "tutorial", text)
text <- gsub("apachekafka", "kafka", text)
text <- gsub("azurepic", "azure", text)
text <- gsub("dddesign", "ddd", text)
text <- gsub("mongo db", "mongodb", text)
text <- gsub("rabbit", "rabbitmq", text)
text <- gsub("webcomponents", "components", text)
text <- gsub("websockets", "sockets", text)
text <- gsub("socket", "sockets", text)
text <- gsub("socketss", "sockets", text)
text <- gsub("virtual reality", "virtualreality", text)
text <- gsub(" vr ", " virtualreality ", text)
text <- gsub("dotnetcore", "dotnet", text)
text <- gsub("servicefabrichttps", "fabric https", text)
text <- gsub("netcore", "dotnet", text)
text <- gsub(" vm ", " virtualization ", text)
text <- gsub("virtualisation", "virtualization", text)
text <- gsub("cloudnativelondon", "cloudnative", text)
text <- gsub("kuberneteshttp", "kubernetes http", text)
text <- gsub("kuberneteshttps", "kubernetes https", text)
text <- gsub("mongodbe", "mongodb", text)
text <- gsub("apidev", "api", text)
text <- gsub("testdriven", "tdd", text)
text <- gsub("testdrivendevelopment", "tdd", text)
text <- gsub("test driven development", "tdd", text)
text <- gsub("testdrivendevelopment", "tdd", text)
text <- gsub("tddpic", "tdd", text)
text <- gsub("apisecurity", "security", text)
text <- gsub("androidappdev", "android", text)
text <- gsub("androiddev", "android", text)
text <- gsub("androidapp", "android", text)
text <- gsub("reliableservices", "reliability", text)
text <- gsub("paaspic", "paas", text)
text <- gsub("iaaspic", "paas", text)
text <- gsub("springpic", "spring", text)
text <- gsub("javaeepic", "javaee", text)
text <- gsub("javapic", "java", text)
text <- gsub("oss", "opensource", text)
text <- gsub("javaone", "opensource", text)
text <- gsub("openlibertyio", "openliberty", text)
text <- gsub("openlibertyibm", "openliberty", text)
text <- gsub("ibmopenliberty", "openliberty", text)
text <- gsub("open liberty", "openliberty", text)
text <- gsub("openlibertypic", "openliberty", text)
text <- gsub("startups", "startup", text)
text <- gsub("springframework", "spring", text)
text <- gsub("dockerpic", "docker", text)
text <- gsub("devopshttps", "devops", text)
text <- gsub("devopshttp", "devops", text)
text <- gsub("webdev", "devops", text)
text <- gsub("mobility", "mobile", text)
text <- gsub("asynchronous", "async", text)
text <- gsub("asynch", "async", text)
text <- gsub(" dl ", " deeplearning ", text)
text <- gsub("restapispic", "rest api", text)
text <- gsub("restapipic", "rest api", text)
text <- gsub("restpic", "rest", text)
text <- gsub("agilepic", "rest", text)
text <- gsub("aipic", "rest", text)
text <- gsub("iotpic", "iot", text)
text <- gsub("testingpic", "iot", text)
text <- gsub("load balancer", "loadbalancing", text)
text <- gsub("load balance", "loadbalancing", text)
text <- gsub("load balancing", "loadbalancing", text)
text <- gsub("mlpic", "machinelearning", text)
text <- gsub("cloudpic", "cloud", text)
text <- gsub("aspnetcore", "aspnet", text)
text <- gsub("dotnetpic", "aspnet", text)
text <- gsub("distributedhttps", "distributed https", text)
text <- gsub("infosecpic", "security", text)
text <- gsub("infosec", "security", text)
text <- gsub("jenkinsworld", "jenkinsworld", text)
text <- gsub("jenkinspic", "jenkins", text)
text <- gsub("apipic", "api", text)
text <- gsub("pythonpic", "python", text)
text <- gsub("rubypic", "api", text)
text <- gsub("retailpic", "retail", text)
text <- gsub("frameworkpic", "framework", text)
text <- gsub("bigdatapic", "bigdata", text)
text <- gsub("integrationpic", "integration", text)
text <- gsub("devopspic", "devops", text)
text <- gsub("awspic", "aws", text)
text <- gsub("osspic", "opensource", text)
text <- gsub("autoscaling", "scalability", text)
text <- gsub("scaling", "scalability", text)
text <- gsub("datapic", "data", text)
text <- gsub("ssdpic", "ssd", text)
text <- gsub("linuxhttps", "linux https", text)
text <- gsub("linuxpic", "linux", text)
text <- gsub("dataanalytics", "data analytics", text)
text <- gsub("cloudanalytics", "cloud analytics", text)
text <- gsub("javascriptpic", "javascript", text)
text <- gsub("rtpic", "rt", text)
text <- gsub("real time", "rt", text)
text <- gsub("real time", "rt", text)
text <- gsub("digitalizationtransformation", "digitalization", text)
text <- gsub("soacloud", "soa cloud", text)
text <- gsub(" tool ", " tools ", text)
text <- gsub(" messages ", " messaging ", text)
text <- gsub(" message ", " messaging ", text)
text <- gsub("message-oriented", "messaging", text)
text <- gsub("event-oriented", "events", text)
text <- gsub("dockercontainers", "docker containers", text)
text <- gsub("amazonwebservices", "aws", text)
text <- gsub("amazon webservices", "aws", text)
text <- gsub("amazon web services", "aws", text)
text <- gsub("mobileapp ", "mobile ", text)
text <- gsub("mobilepic", "mobile", text)
text <- gsub("dockercon ", "docker ", text)

}